# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Check branch diff

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.head_ref }}
    - name: Fetch master
      run: git fetch origin master:master
    - name: get diff
      run: |
        git diff master | grep "^+" >> diff.txt
        cat diff.txt
        echo "::set-output name=git_diff::$git_diff"
      id: get_diff


    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: create checklist
      run: |
        node checklistUtil.js
        create_checklist="$(cat checklist.md)"
        create_checklist="${create_checklist//$'\n'/'%0A'}"
        create_checklist="${create_checklist//$'-'/'%2D'}"
        create_checklist="${create_checklist//$'['/'%5B'}"
        create_checklist="${create_checklist//$']'/'%5D'}"
        echo "::set-output name=create_checklist::$create_checklist"
      id: create_checklist

    - name: check output
      run: echo ${{ steps.create_checklist.outputs.create_checklist }}

    - uses: actions/github-script@v2
      with:
        script: |
          create_checklist="$(cat checklist.md)"
          echo "$create_checklist"
          github.issues.createComment({
            issue_number: context.payload.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: ${{ steps.create_checklist.outputs.create_checklist }}
          })
