# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Check branch diff

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.head_ref }}
    - name: Fetch master
      run: git fetch origin master:master
    - name: get diff
      run: |
        git diff master | grep "^+" >> diff.txt
        cat diff.txt
      id: get_diff

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: create checklist
      run: node checklistUtil.js

#    - name: create checklist
#      run: ./checklist.sh

#    - uses: actions/github-script@v2
#      with:
#        script: |
#          github.issues.createComment({
#            issue_number: context.pull_request.number,
#            owner: context.repo.owner,
#            repo: context.repo.repo,
#            body: '👋 Thanks for reporting!'
#          })
