# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Check branch diff

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.head_ref }}
    - name: Fetch master
      run: git fetch origin master:master
    - name: get diff
      run: |
        git diff master | grep "^+" >> diff.txt
        cat diff.txt
      id: get_diff
    - name: create checklist
      uses: satackey/action-js-inline@v0.0.3
      id: createchecklist
        with:
          required-packages: fs, path
          script: |
            function getFinalChecklist(diff) {
              let checklist = getChecklist(diff);
              let formattedChecklist = getFormattedChecklist(checklist);
              return formattedChecklist;
            }


            function getChecklist(diff) {
              const data = require('./mapping.json');
              const mappings = data.mappings
              let checklist = []

              mappings.forEach(mapping => {
                const keywords = mapping.keywords
                for (let i = 0; i < keywords.length; i++) {
                  if (diff.toLowerCase().includes(keywords[i].toLowerCase())) {
                    checklist.push(mapping.comment)
                    break;
                  }
                }
              })
              return checklist;
            }


            function getFormattedChecklist(checklist) {
              let formattedChecklist = '';
              if (checklist.length > 0) {
                formattedChecklist = '**Checklist:**'

                for (let i = 0; i < checklist.length; i++) {
                  formattedChecklist += '\n';
                  formattedChecklist += '- [ ] ' + checklist[i];
                }
              }
              return formattedChecklist;
            }

            const fs = require('fs')
            var path = require('path');
            var filePath = path.join(__dirname, '..', '..', 'diff.txt');

            fs.readFile(filePath, 'utf8', function (err,data) {
              if (err) {
                return console.log(err);
              }
              let checklist = getFinalChecklist(data);
              console.log(checklist)
            });