# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Dynamic checklist

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.head_ref }}

    - name: Fetch master
      run: git fetch origin master:master

    - name: Get diff
      run: |
        git diff master | grep "^+" >> diff.txt
        cat diff.txt

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Create checklist
      run: |
        node checklistUtil.js

    - uses: actions/github-script@v2
      with:
        script: |
          const fs = require('fs')
          const path = require('path')
          const filePath = path.resolve('./checklist.md')
          fs.readFile(filePath, 'utf8', function (err, data) {
            if (err) {
              return console.log(err);
            }
            data = data.trim()
            if (data.length > 0) {
              github.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: data
              })
            }
          });

